version: '3.0'

services:
    nodejs:
        container_name: nodejs
        build: ./nodejs
        ports:
            - 3000:3000
        restart: always
        volumes:
            - nodejs:/nodejs
        networks:
            - nodejs
    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - 80:80
            - 443:443
        restart: always
        volumes:
            - nginx:/etc/nginx
            - html:/usr/share/nginx/html
        networks:
            - nginx
        links:
            - nodejs

volumes:
    nodejs: {}
    nginx: {}
    html: {}

networks:
    nodejs:
        driver: bridge
    nginx:
        driver: bridge
