version: '3.0'

services:
    nodejs:
        container_name: nodejs
        build: .
        ports:
            - 3000:3000
        restart: always
        volumes:
            - nodejs:/nodejs
volumes:
    nodejs: {}
